### ISSUE TITLE
Key error when trying to select RWKV models.

### ISSUE THREAD

**Issue by 80sVectorz** [henk717/KoboldAI-Client#374]
I downloaded this snapshot: https://github.com/henk717/KoboldAI/releases/tag/Snapshot-7-5-2023
Whenever I click a RWKV model for instance raven 7b the cli show this: 
![84YxwG1cZr](https://github.com/henk717/KoboldAI/assets/66908776/7f3bbee4-dfb0-4666-ad73-c5d88931426f)

**Comment by henk717** [comment]
This is expected since transformers 4.29 and higher breaks our model loader. Its a difficult one to fix so official support takes some time. If you don't care about that you can manually edit our environments/huggingface.yml to have a newer version of transformers and run install_requirements.sh after that.

Once you do that you will loose the ability to load models split between gpu's or cpu/gpu on first load. If you need that ability first load 100% on the CPU and then load the model again with your preferred settings.

**Comment by 80sVectorz** [comment]
Alright, good to know, I'll wait for the new loader to be finished. Good luck with that!

**Comment by 80sVectorz** [comment]
Alright, good to know, I'll wait for the new loader to be finished. Good luck with that!
