### ISSUE TITLE
What is the meaning of this

### ISSUE THREAD

**Issue by ttt845h** [henk717/KoboldAI-Client#381]
Kobold returned error: 507 INSUFFICIENT STORAGE {"detail":{"msg":"KoboldAI ran out of memory: CUDA error: out of memory","type":"out_of_memory.unknown.unknown"}}

**Comment by henk717** [comment]
Normally it would show more information so I don't know why its so little, but your GPU ran out of memory trying to run the model.

**Comment by ttt845h** [comment]
Any fixes? 
Also if this is a second comment im sorry i cant remember
 things well

**Comment by AphidGit** [comment]
There are five fixes to not having enough memory: 

1. Get a bigger (more VRAM) GPU(s). Costs money. 
2. Run some part of the model on the CPU by adjusting 'gpu layers' down. Will slow performance a bit for every layer you move off the GPU. Con 2: will use more RAM. 
3. Use a smaller or more quantized model. Smaller model won't be as good. 
4. Limit the context size. AI will have worse memory.
5. Don't run under windows. It consumes 19% of your gpu memory instead of a fixed amount. 

You might want to provide what model, what GPU, and which OS you use. Are you simply trying to run a model that won't fit, or should it theoretically work but you're still seeing out of memory?
