### ISSUE TITLE
problem with loading Pygmalion-6B

### ISSUE THREAD

**Issue by wilczeu** [henk717/KoboldAI-Client#469]
![kobold-error](https://github.com/henk717/KoboldAI/assets/105659485/bca38e98-3d8e-4fbc-8463-d90b16c20cfa)
![image](https://github.com/henk717/KoboldAI/assets/105659485/4732c876-cdc2-4704-a1f1-a80f6872e7ac)

**Comment by RecoveredApparatus** [comment]
are you trying to load the model on a cpu?

**Comment by henk717** [comment]
Your GPU is not supported / detected so you need to do the ram requirements times 8.
So in order to run the Pygmalion 6B option with Huggingface you need around 64GB of ram in your PC.

Obviously that is not what you want so the first question is if you have a suitable high memory Nvidia GPU, something 12GB and up. If the answer is no then [Koboldcpp ](https://koboldai.org/cpp) is a better solution for you.

I recommend against Pygmalion 6B since it is very old and will instead link you the much better [Pygmalion 2 7B for Koboldcpp](https://huggingface.co/TheBloke/Pygmalion-2-7B-GGUF/resolve/main/pygmalion-2-7b.Q4_K_S.gguf) which you can run on 8GB of ram.

You can also make use of the [KoboldAI Horde](https://lite.koboldai.net), or run different models on our [Colab ](https://koboldai.org/colab) (Pygmalion got banned by Colab)
